###################
# UseOpenMP.cmake #
###################
FIND_PACKAGE(OpenMP QUIET)
OPTION(WITH_OPENMP "Enable OpenMP support?" ${OPENMP_FOUND})

IF(WITH_OPENMP)
  FIND_PACKAGE(OpenMP REQUIRED)
  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
  ADD_DEFINITIONS(-DWITH_OPENMP)
ENDIF()
